"""feat: complete operations and tracking logs database schema

Revision ID: 29856277b88c
Revises: ab75f2680270
Create Date: 2026-07-25 13:59:35.965567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29856277b88c'
down_revision = 'ab75f2680270'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movement_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plate_number', sa.String(length=20), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('details', sa.String(length=255), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('movement_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_movement_history_plate_number'), ['plate_number'], unique=False)

    op.create_table('parking_slots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('court_id', sa.Integer(), nullable=False),
    sa.Column('slot_number', sa.String(length=20), nullable=False),
    sa.Column('is_occupied', sa.Boolean(), nullable=False),
    sa.Column('location_description', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['court_id'], ['courts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('checkpoint_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('checkpoint_id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('verified_by_user_id', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.String(length=20), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['checkpoint_id'], ['checkpoints.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.ForeignKeyConstraint(['verified_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('parking_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parking_slot_id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['parking_slot_id'], ['parking_slots.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('blocking_incidents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parking_record_id', sa.Integer(), nullable=False),
    sa.Column('reporter_user_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parking_record_id'], ['parking_records.id'], ),
    sa.ForeignKeyConstraint(['reporter_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blocking_incidents')
    op.drop_table('parking_records')
    op.drop_table('checkpoint_logs')
    op.drop_table('parking_slots')
    with op.batch_alter_table('movement_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_movement_history_plate_number'))

    op.drop_table('movement_history')
    # ### end Alembic commands ###
