"""feat: create vehicles table model

Revision ID: ab75f2680270
Revises: 8b46a092b3fd
Create Date: 2026-07-25 13:56:14.199241

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab75f2680270'
down_revision = '8b46a092b3fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plate_number', sa.String(length=20), nullable=False),
    sa.Column('brand', sa.String(length=50), nullable=True),
    sa.Column('model', sa.String(length=50), nullable=True),
    sa.Column('color', sa.String(length=30), nullable=True),
    sa.Column('owner_resident_id', sa.Integer(), nullable=True),
    sa.Column('owner_visitor_id', sa.Integer(), nullable=True),
    sa.Column('registered_by_user_id', sa.Integer(), nullable=False),
    sa.Column('registered_at_checkpoint_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_resident_id'], ['residents.id'], ),
    sa.ForeignKeyConstraint(['owner_visitor_id'], ['visitors.id'], ),
    sa.ForeignKeyConstraint(['registered_at_checkpoint_id'], ['checkpoints.id'], ),
    sa.ForeignKeyConstraint(['registered_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vehicles_plate_number'), ['plate_number'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vehicles_plate_number'))

    op.drop_table('vehicles')
    # ### end Alembic commands ###
